import argparse
parser = argparse.ArgumentParser(description="Curriculum Learning for CDFSL-V", conflict_handler='resolve')
parser.add_argument('-j', '--workers', default=6, type=int, metavar='N', help='number of data loading workers (default: 6)')
parser.add_argument('-b', '--batch_size', default=16, type=int, nargs="+", metavar='N', help='mini-batch size')
parser.add_argument('--num_frames', type=int, default=16)
parser.add_argument('--run', type=str, default='debug')
parser.add_argument('--source', type=str, default='K100H51')
parser.add_argument('--target', type=str, default='H51')
parser.add_argument('--load', type=str, default=None)
parser.add_argument('--start_ep', type=int, default='0')
#parser.add_argument('--backbone', type=str, default='R3D')
#parser.add_argument('--copy_list', default=['N', 'Y'], type=str, nargs="+", metavar='N', help='duplicate data in case the dataset is relatively small ([copy source list, copy target list])')
#parser.add_argument('--num_segments', type=int, default=1)
#parser.add_argument('class_file', type=str)
#parser.add_argument('train_source_list', type=str)
#parser.add_argument('train_target_list', type=str)
#parser.add_argument('val_list', type=str)
